libcontainer: kill all processes in container' cgroup
kata-containers/agent pull request #838
Opened 2020-09-14 10:16 UTC by keloyang

reproduce:
cid=$(crictl runp examples/untrusted-podsandbox-config.json)
crictl create  $cid examples/container-config.yaml examples/untrusted-podsandbox-config.json
crictl start $cid
crictl exec -ti  $cid sh

**Don't exit sh and in another console, run crictl stop.**
crictl stop $cid

Fixes: #837.

the root cause is that container exit , but it don't kill the processes in its cgroup, so the cgroup path is busy, and the cgroup path
cannot be deleted.

runc has fix the issue, details for opencontainers/runc#2085

**go dep and go modules are not compatible**

To import v2 or a version after v2 of a dependency package, go module need to add /v2(or a higher version) to the path of import path. take runc for example,
```
require (
        github.com/checkpoint-restore/go-criu/v4 v4.1.0
		...
```
this means runc need github.com/checkpoint-restore/go-criu, and the version of go-criu is v4.1.0, runc import go-criu like this,
```
criu "github.com/checkpoint-restore/go-criu/v4/rpc"
```
if use dep to update vendor fo agent, agent need runc，and runc need go-criu, so dep will try to get github.com/checkpoint-restore/go-criu/v4 
but it is not exist. dep will fail. So we can't use dep to update vendor anymore.

so I change runc code directly in the vendor dir.
Signed-off-by: Shukui Yang <keloyangsk@gmail.com>

2020-09-14 11:24 UTC, fidencio commented
@keloyang, the right way to approach this will be updating the vendored code here: https://github.com/kata-containers/agent/blob/master/Gopkg.toml and then running `dep ensure -update`.

This will generate the changes we need and we can, then, have that added to a commit then opened as a PR.

Please, would you mind to do that and force-push that into this very same branch?

2020-09-14 11:27 UTC, fidencio commented
> @keloyang, the right way to approach this will be updating the vendored code here: https://github.com/kata-containers/agent/blob/master/Gopkg.toml and then running `dep ensure -update`.
> 
> This will generate the changes we need and we can, then, have that added to a commit then opened as a PR.
> 
> Please, would you mind to do that and force-push that into this very same branch?

Ouch, now I see the whole explanation on your PR body. :-/
@kata-agent, opinions?

2020-09-14 11:28 UTC, fidencio commented
@bergwolf, do you think this one is needed on the 2.0-dev branch?

2020-09-14 11:37 UTC, fidencio commented
@keloyang, in any case, @egernst re-worked the runtime part in order to, at least for now, **not** apply cgroups within the VM.
So, for now, this issue is fixed / workedaround.

2020-09-21 07:48 UTC, bergwolf requested changes

2020-09-21 07:48 UTC, bergwolf commented on vendor/github.com/opencontainers/runc/libcontainer/state_linux.go
> +		c.config.Namespaces.PathOf(configs.NEWPID) != "" {
Please do not modify vendor directory directly. The change will be lost next time we update go vendor. If you believe something is broken, please fix it in the original repository (`runc` in this case) and update kata's vendor.conf instead.

2020-09-21 07:52 UTC, bergwolf commented
Ok, I see the reason behind the direct vendor update. However, it is still not acceptable to just modify vendor code directly. Next time we run `dep ensure`, all the changes will be lost.

If `dep` is so broken as shown here, we should consider migrating to `go dep` instead.

2020-09-21 07:54 UTC, fidencio commented
@bergwolf, you did the whole migration for 2.x repo. How do-able would be to backport / rewrite those patches to the 1.x branch?

2020-09-22 07:37 UTC, jodh-intel requested changes
Hi @keloyang - please tal at how to re-vendor a PR:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs
- https://github.com/kata-containers/community/blob/master/VENDORING.md

Here's a "concrete" example from the `runtime` repo (where we do a lot of re-vendoring for packages like `govmm`):

- Here's the change to the `govmm` package itself: https://github.com/intel/govmm/pull/128
- And here's how that change is "re-vendored" into the runtime: https://github.com/kata-containers/runtime/pull/2801

2020-09-23 12:49 UTC, keloyang commented
@bergwolf @jodh-intel  @fidencio I have a try and use "dep ensure -v" to update vendor before I raising this pr, but it always failed, 
the reason is go dep and go modules are not compatible, to import v2 or a version after v2 of a dependency package, go module need to add /v2(or a higher version) to the import path. take runc for example,
```
require (
        github.com/checkpoint-restore/go-criu/v4 v4.1.0
	...
```
this means runc need github.com/checkpoint-restore/go-criu, and the version of go-criu is v4.1.0, runc import go-criu like this,
```
criu "github.com/checkpoint-restore/go-criu/v4/rpc"
```
if use dep to update vendor fo agent,  dep will try to get github.com/checkpoint-restore/go-criu/v4, but it is not exist, only github.com/checkpoint-restore/go-criu exist, so dep will fail.  

I think we can't use dep to update vendor anymore and use go mod is a choice.

2020-10-20 18:34 UTC, egernst commented
> @keloyang, in any case, @egernst re-worked the runtime part in order to, at least for now, **not** apply cgroups within the VM.
> So, for now, this issue is fixed / workedaround.

Actually -- this is still a real issue. My change was specific setting cpuset.cpus/mems in the guest. We do (and should!) set the cgroups still.

What are next steps here for 1.x? Can we confirm this is not an issue in 2.x agent?

2021-05-04 17:53 UTC, fidencio commented
Folks, this PR has been stale and I'm closing it as we're walking towards the **final** 1.13.0 release of the kata-containers-1.x.
From now on, all the development will happen as part of https://github.com/kata-containers/kata-containers/ and fixes should be provided to that repo.

Thanks a lot for your contribution, we're sorry that for some reason it got stale, and we hope to see you around for new adventures in the kata-containers-2.x land.

2021-05-04 17:53 UTC, closed without merging