rootBusPath: create rootBusPath dynamically.
kata-containers/agent pull request #860
Opened 2020-10-26 06:53 UTC by jongwu

Currently, rootBusPath is set as a constant value. Bus this pcie bus path
is not alway static, eg. the rootBus on arm64 is
"/devices/platform/4010000000.pcie/pci0000:00". The address part of
"4010000000.pcie" may vary with the maxMem in qemu so it should not be a
fixed value.

For exmaple:
HIGH PCIE address reserved in qemu on virt is from 0 to 512G. The lower
part of address may be allocated to normal memory. In general, normal memory
is largely less than 256G, so the base address of HIGH PCIE can be 256G.
But, in case the maxmem is large enough, like around 256G, the base address
of HIGH PCIE must be increase, eg. 300G.
In the current implementation of kata-runtime, the maxmem in qemu is the host
memory size. So if the host memory size is large enough, the prefix of the
pci device path name will be different from rootBusPath set in kata-agent which
can lead to failure on device hotplug.

This patch offer a mechanism to create rootBusPath dynamically but only give
implemention for arm64 and return the default value of rootBusPath for other arch.

Fixes: #859
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

@jodh-intel @devimc

2020-10-26 09:00 UTC, alicefr commented
cc @jschintag

2020-10-26 10:48 UTC, dgibson approved these changes
I think this is a good idea.  ppc64 doesn't need this just yet, but at some point it will need the ability to handle multiple PCI roots, and this gets us a little closer to doing that.

2020-10-26 13:14 UTC, devimc commented
/test

2020-10-26 19:24 UTC, devimc approved these changes
thanks @jongwu

2020-10-27 09:30 UTC, jodh-intel requested changes
Hi @jongwu - thanks for raising. I've added some comments so blocking PR for now...

2020-10-27 09:30 UTC, jodh-intel commented on device_arm64.go
> +	// find out the director end with ".pcie"
Is this a typo ("directory" rather than "director")?

2020-10-27 09:30 UTC, jodh-intel commented on device_arm64.go
> +		if strings.HasSuffix(file.Name(), ".pcie") {
If the comment above has a typo, shouldn't this also test that `file.IsDir() == true`?

2020-10-27 09:30 UTC, jodh-intel commented on device_arm64.go
> +	return ""
What does returning `""` mean? Is that a valid scenario or should this function actually return `(string, error)`?

2020-10-27 09:30 UTC, jodh-intel commented on device_arm64.go
> +		fmt.Errorf("Error reading %s: %s", sysStartRootBusPath, err)
This suggests the function should be returning an `error` to me...?

2020-10-27 11:32 UTC, jodh-intel approved these changes
Thanks @jongwu.

lgtm

2020-10-27 11:32 UTC, jodh-intel commented
/test

2020-10-27 11:33 UTC, jodh-intel commented
@jongwu - Travis is failing - looks like you need to update the tests for the latest changes.

2020-10-27 12:18 UTC, jongwu commented
thanks @jodh-intel , I have fixed it. now could you please retrigger ci again?

2020-10-27 13:29 UTC, jodh-intel commented
/test

2020-10-27 13:56 UTC, jongwu commented
hello @jodh-intel -, I can't see ARM CI, could please trigger it?

2020-10-27 14:08 UTC, jodh-intel commented
/test-arm

@jongwu - I've added you to the runtime + agent repos so you should be able to trigger builds yourself from now on. Also, are you planning to port this to the new 2.0 rust agent?

2020-10-27 20:49 UTC, amshinde approved these changes

2020-10-27 20:53 UTC, amshinde commented
/test-arm

2020-10-27 20:54 UTC, amshinde commented
Dont see an ARM CI.
@chavafg Is it not enabled for the agent?

2020-10-27 23:04 UTC, chavafg commented
hmm, yeah, it seems that arm CI has not been enabled for this repo. @jongwu could you help adding it? let me know if you need help.

2020-10-28 02:15 UTC, jongwu commented
/test-arm

2020-10-28 05:05 UTC, jongwu commented
/test

2020-10-28 06:45 UTC, jongwu commented
/test

2020-10-28 06:46 UTC, jongwu commented
/test

2020-10-30 08:53 UTC, jongwu commented
Thanks @jodh-intel -, I have composed the rust version of this patch, see [rust](https://github.com/kata-containers/kata-containers/pull/1060). It's not easy for me to write rust code.

2020-10-30 09:03 UTC, jodh-intel commented
Thanks @jongwu! No problem - we can help if necessary :smile:

2020-10-30 09:37 UTC, jongwu commented
thanks @jodh-intel .

2020-11-26 03:38 UTC, jongwu commented
Hello @jodh-intel @chavafg, all tests pass. isn't time to merge this?

2020-11-26 13:01 UTC, merged